version: '3.8'
services:
  cups:
    image: olbat/cupsd:latest
    container_name: cups_server
    restart: always
    ports:
      - "631:631" # Puerto est치ndar para el servicio CUPS
    volumes:
      - ./cups-data:/etc/cups       # Persistencia de la configuraci칩n de CUPS
      - ./printers:/var/spool/cups  # Persistencia de las colas de impresi칩n
      - ./logs:/var/log/cups        # Logs de CUPS
      - /dev/usb:/dev/usb           # Acceso a impresoras USB
    environment:
      - CUPS_ADMIN_USERNAME=admin  # Usuario administrador
      - CUPS_ADMIN_PASSWORD=admin  # Contrase침a administrador
